### ISSUE TITLE
ios11.2锁屏后wifi断开

### ISSUE THREAD

**Issue by byheaven** [ThomasLee969/CampNet#3]
测试发现安装CampNet之后，锁屏一段时间后wifi会断开，是否开启自动登录的原因？貌似关闭自动登录后问题依然存在。
网络环境：Tsinghua内有线网络，使用无线路由器连接。

**Comment by ClumsyLee** [comment]
首先感谢你的反馈！

我之前也遇到过类似的问题，排查之后的结论是这可能是 iOS 的问题，就算不装 CampNet 也会这样。网上似乎也有类似的结论（https://www.tanaza.com/blog/wifi-disconnects-sleep-mode-iphone-6s-ios-devices-problem-solved/）

如果怀疑是 CampNet 的问题，可以尝试卸载后看看症状是否还在。

**Comment by byheaven** [comment]
卸载后没再出现了，因为之前也遇到过类似的情况，很多人反应是“腾讯手机管家”之类软件中的Wi-Fi管理模块造成的（类似万能钥匙那种自动连入的功能），所以怀疑是不是campnet也是用了类似的自动登录方法，导致触发了iOS的bug？

**Comment by ClumsyLee** [comment]
确实使用了这样的 API，倒不如说这个 app 能写出来就靠了这个 API 😂 这一块的核心逻辑在 https://github.com/ThomasLee969/CampNet/blob/master/CampNetKit/Extensions/NEHotspotHelperCommandExtensions.swift ，不过我暂时没有发现问题…

如果再次遇到这种情况，能否麻烦将 log 发给我看看呢，我这部分所有操作都 log 下来了的 😂 log 在设置中可以找到。不过 app 在后台被掐了就会清空。只要出现状况马上进 app 找到 log 就行了。

太感谢了！

**Comment by byheaven** [comment]
今天重新安装，又出现了同样的现象，锁屏后解锁时会看到wifi先断开然后再出现，日志如下：

[campnet.txt](https://github.com/ThomasLee969/CampNet/files/1473450/campnet.txt)

**Comment by ClumsyLee** [comment]
已经通过反馈收到了，我正在查看，十分感谢！

**Comment by byheaven** [comment]
又测试了一下，关掉当前WiFi的“校园内”选项，问题不会再出现了

**Comment by ClumsyLee** [comment]
麻烦问一下，是出现了这个状况后马上复制了日志吗？我有点不太确定具体对应日志的哪个阶段。如果是马上复制的，日志里最后一段大概讲述的是这样的过程：

```
0.0s: 收到 WI-FI 列表
0.0s: 返回已知 Wi-Fi 列表（J*******5G）
0.0s: 系统让 CampNet 认证该 Wi-Fi
0.1s: 访问 net.tsinghua 查看状态
0.2s: 收到回复
4.8s: 处理完毕，发现仍然在线
4.8s: 答复系统认证成功
```

我也又调查了一番，其中[最详尽的一篇文章](http://gmd20.github.io/blog/iPhone连接wifi热点跳转captive-portal页面原理以及页面跳转慢原因分析/)里面提到：

> 苹果锁屏后屏幕关闭后，如果手机没有一直充电，wifi会自动断开。等重新点亮屏幕之后才重新链接wifi

所以我现在的分析是，这个问题主要是 CampNet 回复慢了（处理效率偏低，在后台用了约 5s），导致 iOS 短暂显示断线。未安装时因为重连速度很快（没有 CampNet 消耗的 5s）可能察觉不到，或者 UI 直接显示一直在线。不知道这和你的感觉是否相符？（例如断线约 5s 重连？）

所以我找机会好好优化一下代码 orz 最近找实习有点忙，有点耽搁了，实在抱歉 🙏

**Comment by ClumsyLee** [comment]
> 又测试了一下，关掉当前WiFi的“校园内”选项，问题不会再出现了

关掉这个选项 CampNet 在第二步就会告诉系统，自己处理不了这个 Wi-Fi 了。实际上和未安装 CampNet 没有区别。你可以看下我上面的回复是否与你的感官相符 😂

**Comment by byheaven** [comment]
嗯，看了下那篇文章，应该是这么个情况，日志里就是最后一段是断线的部分。不过这问题其实不影响使用，手动连接一下也不费事。
p.s. 祝找到心仪的实习~

**Comment by byheaven** [comment]
另外我想，其实通过网页认证的方式登录，并不需要经常的重新认证，会保持在线比较长时间。那app里是不是也可以不是每次开屏时都进行认证请求呢？

**Comment by ClumsyLee** [comment]
是这样子的，iOS 从 iOS 9 开始开放了这个接口，但这个接口很有限（iOS 里没有真正的后台），实际上是 iOS 自己有一个状态机，然后 app 可以定制每一步的操作：

![a7263c67-1b9c-4da1-8975-c0b9a8e9a804](https://user-images.githubusercontent.com/7030671/32823438-16078a7c-c992-11e7-9ff6-a3749c11e10a.png)

对于你说的那种情况，Apple 实际上是考虑到了。第一次链接 Wi-Fi 是 `evaluate -> authenticate`, 你说的这种情况就直接 `maintain` 了。但具体到 CampNet，为了确定确实还在线，CampNet 还是得访问一下 `net.tsinghua.edu.cn`。其实这一步很快的，从 log 可以看出只用了 `0.1s` 就收到了回复，但问题就出在处理速度上…

当然，这里一种解决方式是，iOS 让我 `maintain` 时，我直接返回成功。但这之后就没有补救的机会了，因为 iOS 调用 CampNet 处理完之后又会让 CampNet 休眠……

所以关键就在处理速度其实 😂

**Comment by ClumsyLee** [comment]
另外十分感谢你对 CampNet 的支持！因为我现在毕业了在留学，不知道下次回国调试是哪天，所以你们对 CampNet 的支持真的十分宝贵。特别是，CampNet 本身就是为了适配不同学校校园网设计（添加配置文件就可以适配新网络），但我弄了咱清华的之后就出来了，很不甘心…

所以如果方便的话，请务必向身边的朋友同学推荐一下 CampNet！

**Comment by byheaven** [comment]
客气了，很支持你能业余时间做这样的事情，我已经向周围的人推荐了，因为确实无论从UI还是开源还是可以扩展到不同学校这样的想法，CampNet都是很棒的。虽然我不是计算机的（我6字班基科，现在还在做博后，在清华11年了。。。），不过一直以来能够发现类似CampNet这样的优秀作品都让我感到开心，因此也都会比较仔细的去使用发现问题。
所以，继续加油！

**Comment by byheaven** [comment]
另外，还有个不知道对不对的想法，在iTunet里，除了“自动登录”以外，还有一个“允许后台自动刷新”的开关。所以我在想，是不是可以利用现在iOS的“后台应用刷新”机制，实现上面说的一些处理办法呢？
也希望有更多的大牛同学能够看到这样的项目，然后加入进来一起完善。

**Comment by ClumsyLee** [comment]
谢谢学长！我是三字班电子的，虽然不是科班出身，但对这方面确实有一种莫名的执念… 所以现在也在往这方面发展其实 😂

关于 iTunet（我原来也是它的用户，但感觉不太够用），我之前也注意到了这个选项，但没太在意，刚刚看了下似乎确实有这么回事，我找机会研究下！

不过现在的这个问题，主要还是要靠优化解决我感觉。毕竟这里 5s 太过夸张了，几乎肯定是我没写好…🌚

**Comment by byheaven** [comment]
嗯，加油！这种执念我深有体会。。。。

**Comment by ClumsyLee** [comment]
Should be mitigated in 1.3.0.
