### ISSUE TITLE
宿舍有线网更新认证方式后，用无线路由器APP无法识别

### ISSUE THREAD

**Issue by jzz3933** [ThomasLee969/CampNet#9]
1.宿舍有线网更新认证方式，利用auth4.tsinghua.edu.cn认证，用net.tsinghua.edu.cn无法认证（且访问其他网页，均不会跳转到认证页面），这时用无线路由器转为无线后，APP无法识别为校园网，并且无法上线，但是网页认证后，用APP好像可以下线

2.如果想自己写认证配置，大概是什么步骤呢？楼主有没有推荐的教程之类的呢？

**Comment by ClumsyLee** [comment]
1. 这个问题现在已知，有线网实名认证之后我暂时没机会更新，等期末完了我搞一搞 orz
2. 配置的 repo 在这里：[CampNet-Configurations](https://github.com/ThomasLee969/CampNet-Configurations)，大致上需要知道一些 js 的知识。你看一下现在的 `cn.edu.tsinghua.yaml` 应该就大体明白了。

**Comment by jzz3933** [comment]
好的，看到了，感谢你的付出，程序很好用，预祝期末顺利

**Comment by jzz3933** [comment]
之前没有对这方面进行研究，再请教一下
1.如果针对新的认证方式，想自己写个配置的话，假如只实现上线、下线功能的话，除了yaml配置文件中的网址需要更新，还有其他需要注意的地方吗？我看有好几个位置写了上线、下线操作，有点疑惑。

2.再问一个小白问题，如果写了配置文件后，是要在github上进行某种操作就可以在IOS的APP中找到对应的配置文件了吗？

多谢多谢，如果过程太麻烦的话，楼主就先准备考试，闲了再聊就可以的，最后加个油啦

**Comment by ClumsyLee** [comment]
1. 最少要实现 `status`, `login`，你看到的几个上线应该是上线 usereg 获取账户信息之类的。
2. 我是想那么弄的，但偷懒了还没写……现在必须要我发新版本才可以。这个也是我准备弄的东西 😂

编辑：忘说了还有 `logout`。

**Comment by jzz3933** [comment]
好的，略懂略懂，我再研究一下，感谢！！

**Comment by ClumsyLee** [comment]
你好（抱歉回复的如此之晚 😂），我最近想继续开发，请问你研究清楚了吗，auth4 和 net 只有 URL 的区别吗，还是有其他的区别 0.0

**Comment by ClumsyLee** [comment]
Done in 1.3.0.
